kind: Deployment
apiVersion: apps/v1
metadata:
  name: tdpgiswebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tdpgiswebapp
  template:
    metadata:
      labels:
        app: tdpgiswebapp
    spec:
      containers:
      - name: tdpgiswebapp
        image: bobpham/tdpgiswebapp:main_20220602_1
        resources:
          limits:
            memory: "550Mi"
            cpu: "500m"
        ports:
        - containerPort: 80